import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {AddressInfo} from 'node:net';
import type {RowDataPacket} from 'mysql2/promise';
import {createPool} from '../server/db.ts';
import {migrate} from '../server/migrate.ts';
import {createApp} from '../server/app.ts';

test('admin user management is paginated, transactional and preserves access and votes',async()=>{
 const pool=createPool(true);await migrate(pool);const suffix=randomUUID().slice(0,8),password=randomUUID()+'Aa1!',userIds:string[]=[],pollIds:number[]=[];
 const server=createApp(pool,'http://localhost:5175').listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api`;
 function client(){const jar=new Map<string,string>();let csrf='';return {async call(path:string,method='GET',body?:unknown){const response=await fetch(base+path,{method,headers:{Origin:'http://localhost:5175','Content-Type':'application/json','X-CSRF-Token':csrf,cookie:[...jar].map(([k,v])=>`${k}=${v}`).join('; ')},body:body===undefined?undefined:JSON.stringify(body)});for(const value of response.headers.getSetCookie()){const pair=value.split(';')[0],at=pair.indexOf('=');jar.set(pair.slice(0,at),pair.slice(at+1));}const data=await response.json();if(path==='/csrf')csrf=data.token;return {status:response.status,data};}};}
 const admin=client(),reader=client();
 try{
  await admin.call('/csrf');const a=await admin.call('/auth/register','POST',{email:`admin-users-${suffix}@example.test`,password});userIds.push(a.data.user.id);await pool.execute("UPDATE users SET role='admin' WHERE id=?",[a.data.user.id]);
  await reader.call('/csrf');const r=await reader.call('/auth/register','POST',{email:`target-${suffix}@example.test`,password});const target=r.data.user.id;userIds.push(target);await pool.execute('UPDATE users SET key_balance=5 WHERE id=?',[target]);
  assert.equal((await reader.call('/admin/users')).status,403);
  for(let index=0;index<23;index++){const id=randomUUID();userIds.push(id);await pool.execute('INSERT INTO users(id,email,password_hash,key_balance) VALUES(?,?,?,?)',[id,`paging-${suffix}-${String(index).padStart(2,'0')}@example.test`,'test-only',index]);}
  const stats=await admin.call('/admin/users/stats');assert.equal(stats.status,200);assert.ok(stats.data.readers.total>=24);assert.ok(stats.data.administrators>=1);
  const first=await admin.call(`/admin/users?page=1&search=${encodeURIComponent(` paging-${suffix} `)}`),second=await admin.call(`/admin/users?page=2&search=${encodeURIComponent(`PAGING-${suffix}`)}`);assert.equal(first.data.items.length,20);assert.equal(second.data.items.length,3);assert.equal(new Set([...first.data.items,...second.data.items].map((item:any)=>item.id)).size,23);
  const cleared=await admin.call('/admin/users?page=1&search=');assert.ok(cleared.data.total>=24);const searched=await admin.call(`/admin/users?page=1&search=${encodeURIComponent(`TARGET-${suffix}`)}`);assert.equal(searched.data.items[0].id,target);assert.equal(searched.data.items[0].keyBalance,5);
  const creditKey=randomUUID(),credit=await admin.call(`/admin/users/${target}/keys`,'POST',{operation:'credit',value:10,reason:'Site testing',idempotencyKey:creditKey});assert.equal(credit.status,201);assert.equal(credit.data.keyBalance,15);const duplicate=await admin.call(`/admin/users/${target}/keys`,'POST',{operation:'credit',value:10,reason:'Site testing',idempotencyKey:creditKey});assert.equal(duplicate.status,200);assert.equal(duplicate.data.keyBalance,15);assert.equal(duplicate.data.duplicate,true);
  const debit=await admin.call(`/admin/users/${target}/keys`,'POST',{operation:'debit',value:3,reason:'Correction',idempotencyKey:randomUUID()});assert.equal(debit.data.keyBalance,12);
  await admin.call(`/admin/users/${target}/keys`,'POST',{operation:'set',value:2,reason:'Prepare insufficient test',idempotencyKey:randomUUID()});const beforeJournal=(await admin.call(`/admin/users/${target}/key-transactions`)).data.total;const insufficient=await admin.call(`/admin/users/${target}/keys`,'POST',{operation:'debit',value:5,reason:'Must fail',idempotencyKey:randomUUID()});assert.equal(insufficient.status,409);assert.equal((await admin.call(`/admin/users/${target}/key-transactions`)).data.total,beforeJournal);
  await admin.call(`/admin/users/${target}/keys`,'POST',{operation:'set',value:5,reason:'Prepare set test',idempotencyKey:randomUUID()});const exact=await admin.call(`/admin/users/${target}/keys`,'POST',{operation:'set',value:30,reason:'Manual correction',idempotencyKey:randomUUID()});assert.deepEqual([exact.data.transaction.balanceBefore,exact.data.transaction.amountDelta,exact.data.transaction.balanceAfter],[5,25,30]);const journal=await admin.call(`/admin/users/${target}/key-transactions`);assert.equal(journal.data.items.filter((item:any)=>item.operation==='admin_credit'&&item.amountDelta===10).length,1);assert.ok(journal.data.items.every((item:any)=>item.adminEmail===`admin-users-${suffix}@example.test`));
  const [chapters]=await pool.query<RowDataPacket[]>('SELECT c.id,c.heroine_id,c.published_revision,v.document,c.key_cost FROM chapters c JOIN chapter_versions v ON v.chapter_id=c.id AND v.revision=c.published_revision WHERE c.published_revision IS NOT NULL LIMIT 1');const chapter=chapters[0],document=typeof chapter.document==='string'?JSON.parse(chapter.document):chapter.document,sceneId=document.chapter.firstScene;
  await pool.execute('INSERT INTO progress(user_id,heroine_id,chapter_id,story_revision,scene_id,completed_scenes,choices,decisions,save_version) VALUES(?,?,?,?,?,JSON_ARRAY(),JSON_OBJECT(),JSON_ARRAY(),1)',[target,chapter.heroine_id,chapter.id,chapter.published_revision,sceneId]);await pool.execute('INSERT INTO chapter_unlocks(user_id,chapter_id,key_cost) VALUES(?,?,?)',[target,chapter.id,Number(chapter.key_cost)]);
  const [pollResult]=await pool.execute<any>("INSERT INTO polls(admin_title,question,description,type,status,allow_skip,show_results,allow_vote_change) VALUES('User reset fixture','Choose','Fixture','opinion','active',TRUE,FALSE,FALSE)");const pollId=Number(pollResult.insertId);pollIds.push(pollId);const [optionResult]=await pool.execute<any>("INSERT INTO poll_options(poll_id,text,description,sort_order) VALUES(?,'One','',0)",[pollId]);await pool.execute('INSERT INTO poll_votes(poll_id,option_id,user_id) VALUES(?,?,?)',[pollId,Number(optionResult.insertId),target]);await pool.execute("INSERT INTO poll_progress(poll_id,user_id,status) VALUES(?,?,'voted')",[pollId,target]);
  const reset=await admin.call(`/admin/users/${target}/reset-progress`,'POST',{confirmation:`target-${suffix}@example.test`});assert.equal(reset.status,200);assert.equal(reset.data.deletedProgressRows,1);const [afterProgress]=await pool.execute<RowDataPacket[]>('SELECT 1 FROM progress WHERE user_id=?',[target]),[afterUnlock]=await pool.execute<RowDataPacket[]>('SELECT 1 FROM chapter_unlocks WHERE user_id=? AND chapter_id=?',[target,chapter.id]),[afterVote]=await pool.execute<RowDataPacket[]>('SELECT 1 FROM poll_votes WHERE user_id=? AND poll_id=?',[target,pollId]),[afterPoll]=await pool.execute<RowDataPacket[]>('SELECT status FROM poll_progress WHERE user_id=? AND poll_id=?',[target,pollId]),[afterUser]=await pool.execute<RowDataPacket[]>('SELECT key_balance FROM users WHERE id=?',[target]);assert.equal(afterProgress.length,0);assert.equal(afterUnlock.length,1);assert.equal(afterVote.length,1);assert.equal(afterPoll[0].status,'voted');assert.equal(Number(afterUser[0].key_balance),30);
  const detail=await admin.call(`/admin/users/${target}`);assert.equal(detail.status,200);assert.equal(detail.data.password_hash,undefined);assert.equal(detail.data.keyBalance,30);assert.equal(detail.data.unlocks.length,1);assert.equal(detail.data.progress.length,0);
 }finally{
  for(const id of pollIds){await pool.execute('DELETE FROM poll_progress WHERE poll_id=?',[id]);await pool.execute('DELETE FROM poll_votes WHERE poll_id=?',[id]);await pool.execute('DELETE FROM poll_options WHERE poll_id=?',[id]);await pool.execute('DELETE FROM polls WHERE id=?',[id]);}
  for(const id of userIds){await pool.execute('DELETE FROM progress WHERE user_id=?',[id]);await pool.execute('DELETE FROM chapter_unlocks WHERE user_id=?',[id]);await pool.execute('DELETE FROM key_transactions WHERE user_id=? OR admin_id=?',[id,id]);await pool.execute('DELETE FROM plan_analytics_events WHERE user_id=?',[id]);await pool.execute('DELETE FROM analytics_events WHERE user_id=?',[id]);await pool.execute('DELETE FROM users WHERE id=?',[id]);}
  await new Promise<void>(resolve=>server.close(()=>resolve()));await pool.end();
 }
});
