import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {AddressInfo} from 'node:net';
import type {RowDataPacket} from 'mysql2/promise';
import {createPool} from '../server/db.ts';
import {migrate} from '../server/migrate.ts';
import {createApp} from '../server/app.ts';
import type {Story} from '../src/story-model.ts';

test('guest access, transfer, poll skip and one-key chapter unlock',async()=>{
 const pool=createPool(true);await migrate(pool);const suffix=randomUUID().slice(0,8),hero=`guest-${suffix}`,first=`free-${suffix}`,second=`paid-${suffix}`,pollIds:number[]=[];
 const extra=[0,1,2].map(i=>`preview-${i}-${suffix}`),users:string[]=[];
 let priorGuestFree:string[]=[];
 const server=createApp(pool,'http://localhost:5175').listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));
 const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api`;
 function client(){const jar=new Map<string,string>();let csrf='';return {jar,async call(path:string,method='GET',body?:unknown){const response=await fetch(base+path,{method,headers:{Origin:'http://localhost:5175','Content-Type':'application/json','X-CSRF-Token':csrf,cookie:[...jar].map(([k,v])=>`${k}=${v}`).join('; ')},body:body===undefined?undefined:JSON.stringify(body)});for(const cookie of response.headers.getSetCookie()){const pair=cookie.split(';')[0],at=pair.indexOf('=');jar.set(pair.slice(0,at),pair.slice(at+1));}const data=await response.json();if(path==='/csrf')csrf=data.token;return {status:response.status,data};}};}
 const browser=client(),chooser=client(),password=randomUUID();
 const media={type:'image' as const,src:'/media/jessica-city.jpg',alt:'Test'};
 const oneScene=(chapterId:string,heroineId:string):Story=>({chapter:{id:chapterId,heroineId,revision:1,title:chapterId,description:'A spoiler-free teaser.',subtitle:'Test',firstScene:'only',freeSteps:1},scenes:{only:{id:'only',type:'story',step:1,title:'Only',text:'Story.',final:true,media,pollId:null,actions:[]}}});
 try{
  const [prior]=await pool.execute<RowDataPacket[]>('SELECT id FROM chapters WHERE guest_free=TRUE');priorGuestFree=prior.map(row=>String(row.id));await pool.execute('UPDATE chapters SET guest_free=FALSE WHERE guest_free=TRUE');
  const [pollResult]=await pool.execute<any>("INSERT INTO polls(admin_title,question,description,type,status,allow_skip,show_results,allow_vote_change) VALUES('Guest poll','Choose','A question','opinion','active',TRUE,TRUE,FALSE)");const pollId=Number(pollResult.insertId);pollIds.push(pollId);
  await pool.execute("INSERT INTO poll_options(poll_id,text,description,sort_order) VALUES(?,'One','',0),(?,'Two','',1)",[pollId,pollId]);
  await pool.execute('INSERT INTO heroines(id,name,description,media) VALUES(?,?,?,?)',[hero,'Guest story','First story',JSON.stringify(media)]);
  await pool.execute('INSERT INTO chapters(id,heroine_id,title,description,display_order,published_revision,key_cost,guest_free) VALUES(?,?,?,?,0,1,0,TRUE),(?,?,?,?,1,1,1,FALSE)',[first,hero,'Free chapter','The beginning',second,hero,'Paid chapter','The next step']);
  const firstStory:Story={chapter:{id:first,heroineId:hero,revision:1,title:'Free chapter',description:'The beginning',subtitle:'Test',firstScene:'start',freeSteps:3},scenes:{start:{id:'start',type:'story',step:1,title:'Start',text:'Start.',final:false,media,pollId:null,actions:[]},question:{id:'question',type:'poll',step:2,title:'What would you choose?',text:'Think about it.',final:false,pollId,actions:[]},end:{id:'end',type:'story',step:3,title:'End',text:'End.',final:true,media,pollId:null,actions:[]}}};
  await pool.execute("INSERT INTO chapter_versions(chapter_id,revision,status,document) VALUES(?,1,'published',?),(?,1,'published',?)",[first,JSON.stringify(firstStory),second,JSON.stringify(oneScene(second,hero))]);
  for(const [index,id] of extra.entries()){await pool.execute('INSERT INTO heroines(id,name,description,media) VALUES(?,?,?,?)',[id,`Preview ${index}`,'Preview description',JSON.stringify(media)]);const chapter=`${id}-chapter`;await pool.execute('INSERT INTO chapters(id,heroine_id,title,description,display_order,published_revision,key_cost,guest_free) VALUES(?,?,?,?,0,1,1,FALSE)',[chapter,id,'Preview chapter','Preview']);await pool.execute("INSERT INTO chapter_versions(chapter_id,revision,status,document) VALUES(?,1,'published',?)",[chapter,JSON.stringify(oneScene(chapter,id))]);}
  await browser.call('/csrf');assert.equal((await browser.call('/reading/session','POST',{})).status,200);
  const guestCatalog=(await browser.call('/content/catalog')).data;assert.deepEqual(guestCatalog.map((item:any)=>item.id),[hero]);assert.equal(guestCatalog[0].chapters.length,1);assert.equal('keyCost' in guestCatalog[0].chapters[0],false);
  const home=(await browser.call('/content/home')).data;assert.ok(home.stories.some((item:any)=>item.id===hero&&item.publishedChapters===2&&item.hasFreeChapter));assert.ok(extra.every(id=>home.stories.some((item:any)=>item.id===id)));assert.ok(home.stats.publishedChapters>=5);assert.ok(home.stats.illustratedScenes>=5);assert.ok(home.stats.activePolls>=1);assert.equal(home.stats.firstChapterFree,true);assert.equal(home.contactEmail,null);
  await chooser.call('/csrf');await chooser.call('/reading/session','POST',{});let chooserState=(await chooser.call('/reading/open','POST',{heroineId:hero})).data;chooserState=(await chooser.call('/reading/advance','POST',{chapterId:first,actionId:'next',version:chooserState.version})).data;const chooserPoll=(await chooser.call('/polls/'+pollId)).data;assert.equal(chooserPoll.selectedOptionId,null);assert.equal((await chooser.call('/polls/'+pollId+'/results')).data.resultsHidden,true);const chooserAccount=await chooser.call('/auth/register','POST',{email:`poll-choice-${suffix}@example.test`,password:randomUUID()});users.push(chooserAccount.data.user.id);assert.equal((await chooser.call('/polls/'+pollId+'/results')).data.resultsHidden,true);assert.equal((await chooser.call('/polls/'+pollId+'/vote','POST',{optionId:chooserPoll.options[1].id})).status,200);const chooserResult=(await chooser.call('/polls/'+pollId+'/results')).data;assert.equal(chooserResult.total,1);chooserState=(await chooser.call('/reading/state')).data.stories[hero];chooserState=(await chooser.call('/reading/advance','POST',{chapterId:first,actionId:'next',version:chooserState.version})).data;assert.equal(chooserState.progress.sceneId,'end');
  const opened=await browser.call('/reading/open','POST',{heroineId:hero});assert.equal(opened.status,200,JSON.stringify(opened.data));let state=opened.data;assert.equal(state.progress.sceneId,'start');assert.equal((await browser.call('/auth/me')).data.user,null);
  state=(await browser.call('/reading/advance','POST',{chapterId:first,actionId:'next',version:state.version})).data;assert.equal(state.progress.sceneId,'question');
  assert.equal((await browser.call('/polls/'+pollId)).status,200);assert.equal((await browser.call('/polls/'+pollId+'/results')).data.resultsHidden,true);assert.equal((await browser.call('/polls/'+pollId+'/vote','POST',{optionId:1})).status,401);assert.equal((await browser.call('/polls/'+pollId+'/view','POST',{})).status,200);assert.equal((await browser.call('/polls/'+pollId+'/skip','POST',{})).status,200);
  state=(await browser.call('/reading/advance','POST',{chapterId:first,actionId:'next',version:state.version})).data;assert.equal(state.progress.sceneId,'end');
  const finished=await browser.call('/reading/finish','POST',{chapterId:first});assert.equal(finished.data.state.mode,'complete');assert.equal(finished.data.state.completionPreview.nextChapter.id,second);assert.equal(finished.data.state.completionPreview.nextChapter.media.src,media.src);assert.equal(finished.data.state.completionPreview.stories.length,3);assert.equal((await browser.call('/content/chapters/'+second)).status,403);
  const registered=await browser.call('/auth/register','POST',{email:`guest-${suffix}@example.test`,password});assert.equal(registered.status,200);const userId=registered.data.user.id;users.push(userId);assert.equal(registered.data.user.keyBalance,0);
  const accountState=(await browser.call('/reading/state')).data.stories[hero];assert.equal(accountState.mode,'awaiting');assert.equal(accountState.chapterId,second);assert.equal(accountState.chapterCost,1);assert.equal(accountState.chapterUnlocked,false);
  const [copied]=await pool.execute<RowDataPacket[]>('SELECT status FROM poll_progress WHERE poll_id=? AND user_id=?',[pollId,userId]);assert.equal(copied[0].status,'skipped');
  const fullCatalog=(await browser.call('/content/catalog')).data;assert.ok(fullCatalog.length>=4);assert.equal(fullCatalog.find((item:any)=>item.id===hero).chapters[1].keyCost,1);
  assert.equal((await browser.call('/reading/open','POST',{heroineId:hero})).status,402);
  assert.equal((await browser.call('/auth/logout','POST',{})).status,200);assert.equal((await browser.call('/auth/me')).data.user,null);assert.equal((await browser.call('/reading/state')).data.stories[hero].mode,'complete');
  assert.equal((await browser.call('/auth/login','POST',{email:`guest-${suffix}@example.test`,password})).status,200);assert.equal((await browser.call('/reading/state')).data.stories[hero].chapterId,second);
  await pool.execute('UPDATE users SET key_balance=1 WHERE id=?',[userId]);const unlocked=await browser.call('/reading/unlock','POST',{heroineId:hero,chapterId:second});assert.equal(unlocked.status,200);assert.equal(unlocked.data.keyBalance,0);assert.equal(unlocked.data.state.chapterUnlocked,true);
  const again=await browser.call('/reading/unlock','POST',{heroineId:hero,chapterId:second});assert.equal(again.status,200);assert.equal(again.data.keyBalance,0);assert.equal(again.data.alreadyUnlocked,true);
  assert.equal((await browser.call('/reading/open','POST',{heroineId:hero})).status,200);assert.equal((await browser.call('/auth/logout','POST',{})).status,200);assert.equal((await browser.call('/auth/login','POST',{email:`guest-${suffix}@example.test`,password})).status,200);assert.equal((await browser.call('/reading/state')).data.stories[hero].chapterId,second);
  const [events]=await pool.execute<RowDataPacket[]>("SELECT event_type FROM analytics_events WHERE user_id=? OR guest_id=(SELECT guest_id FROM progress WHERE chapter_id=? LIMIT 1)",[userId,first]);assert.ok(events.some(row=>row.event_type==='registration_completed'));assert.ok(events.some(row=>row.event_type==='guest_progress_transferred'));
 }finally{
  for(const id of users){await pool.execute('DELETE FROM key_transactions WHERE user_id=? OR admin_id=?',[id,id]);await pool.execute('DELETE FROM analytics_events WHERE user_id=?',[id]);await pool.execute('DELETE FROM users WHERE id=?',[id]);}
  for(const activeClient of [browser,chooser]){const token=activeClient.jar.get('jessica_guest');if(token){const {createHash}=await import('node:crypto');const tokenHash=createHash('sha256').update(token).digest('hex');const [guests]=await pool.execute<RowDataPacket[]>('SELECT id FROM guest_sessions WHERE token_hash=?',[tokenHash]);if(guests[0])await pool.execute('DELETE FROM analytics_events WHERE guest_id=?',[guests[0].id]);await pool.execute('DELETE FROM guest_sessions WHERE token_hash=?',[tokenHash]);}}
  for(const id of [hero,...extra]){const [chapters]=await pool.execute<RowDataPacket[]>('SELECT id FROM chapters WHERE heroine_id=?',[id]);for(const chapter of chapters){await pool.execute('DELETE FROM chapter_versions WHERE chapter_id=?',[chapter.id]);await pool.execute('DELETE FROM chapters WHERE id=?',[chapter.id]);}await pool.execute('DELETE FROM heroines WHERE id=?',[id]);}
  for(const id of pollIds){await pool.execute('DELETE FROM poll_progress WHERE poll_id=?',[id]);await pool.execute('DELETE FROM poll_views WHERE poll_id=?',[id]);await pool.execute('DELETE FROM poll_votes WHERE poll_id=?',[id]);await pool.execute('DELETE FROM poll_options WHERE poll_id=?',[id]);await pool.execute('DELETE FROM polls WHERE id=?',[id]);}
  for(const id of priorGuestFree)await pool.execute('UPDATE chapters SET guest_free=TRUE,key_cost=0 WHERE id=?',[id]);
  await new Promise<void>(resolve=>server.close(()=>resolve()));await pool.end();
 }
});
