CREATE TABLE IF NOT EXISTS users (
 id CHAR(36) PRIMARY KEY,
 email VARCHAR(254) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY,
 user_id CHAR(36) NOT NULL,
 expires_at DATETIME(3) NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX session_expiry (expires_at)
);
CREATE TABLE IF NOT EXISTS progress (
 user_id CHAR(36) NOT NULL,
 heroine_id VARCHAR(64) NOT NULL,
 chapter_id VARCHAR(64) NOT NULL,
 story_revision INT NOT NULL,
 scene_id VARCHAR(64) NOT NULL,
 choices JSON NOT NULL,
 decisions JSON NOT NULL,
 save_version INT UNSIGNED NOT NULL,
 updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 PRIMARY KEY (user_id, heroine_id, chapter_id),
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
