export type Media = ({ type: 'image'; src: string; alt: string } | { type: 'video'; src: string; poster: string; alt: string }) & { caption?: string };
export type Action = { id: string; label: string; target: string; choice?: { key: string; value: string } };
export type Scene = { id: string; step: number; kind?: 'demo' | 'preview'; title: string; text: string; media: Media; variants?: { key: string; value: string; text: string }[]; actions: Action[] };
const artwork: Record<string, { file: string; alt: string }> = {
  portrait: { file: 'jessica-portrait.jpg', alt: 'Portrait of Jessica in warm daylight' },
  arrival: { file: 'jessica-city.jpg', alt: 'Jessica with a suitcase on a sunny city street' },
  river: { file: 'jessica-walk.jpg', alt: 'Jessica outdoors on a tree-lined path beside the water' },
};
const media = (name: string): Media => artwork[name]
  ? { type: 'image', src: `/media/${artwork[name].file}`, alt: artwork[name].alt, caption: 'Jessica · Story illustration' }
  : { type: 'image', src: `/media/${name}.svg`, alt: `${name} — illustrated placeholder for future story media`, caption: 'Illustrated placeholder · Story artwork to come' };
export const heroine = { id: 'jessica', name: 'Jessica', tagline: 'A new city. A little courage. Your next choice.', description: 'At 24, Jessica is starting over in a city she barely knows. Spend her first afternoon with her, and decide where curiosity takes her.', media: media('portrait') };
export const chapter = { id: 'first-day', revision: 1, title: 'A place to begin', subtitle: 'Chapter 01 · First day in the city', firstScene: 'arrival', freeSteps: 5 };
export const scenes: Record<string, Scene> = {
  arrival: { id: 'arrival', step: 1, title: 'One suitcase. A whole new city.', text: 'Jessica steps off the tram with a suitcase and the key to her new apartment. At 24, this is the first place she has chosen entirely for herself. There is still an afternoon to fill before unpacking.', media: media('arrival'), actions: [{ id: 'begin', label: 'Explore the neighborhood', target: 'crossroads' }] },
  crossroads: { id: 'crossroads', step: 2, title: 'An afternoon with no plans', text: 'On the corner, a café door stands open. Across the street, a tree-lined path follows the river. Jessica puts her phone away. Where should she go first?', media: media('crossroads'), actions: [{ id: 'cafe', label: 'Step into the café', target: 'cafe', choice: { key: 'afternoon', value: 'cafe' } }, { id: 'walk', label: 'Take a walk by the river', target: 'river', choice: { key: 'afternoon', value: 'walk' } }] },
  cafe: { id: 'cafe', step: 3, title: 'A seat by the window', text: 'Jessica orders tea and finds a sunny table. Beside the counter, a hand-drawn notice announces a book exchange in the neighborhood square. She writes down the address on her receipt. Her first local recommendation.', media: media('cafe'), actions: [{ id: 'to-square', label: 'Find the neighborhood square', target: 'square' }] },
  river: { id: 'river', step: 3, title: 'Room to breathe', text: 'The river path is quieter than the main street. Jessica pauses on a footbridge, watching the water catch the light. A sign points toward a book exchange in the neighborhood square. She decides to follow it.', media: media('river'), actions: [{ id: 'to-square', label: 'Follow the sign to the square', target: 'square' }] },
  square: { id: 'square', step: 4, title: 'Something in common', text: 'A little shelf of shared books sits beneath a tree. Jessica picks up a collection of short stories. A note inside reads: “Leave a favorite. Find a new one.” She already knows which book she will bring tomorrow.', variants: [{ key: 'afternoon', value: 'cafe', text: 'The address on her café receipt has led her to exactly the right place.' }, { key: 'afternoon', value: 'walk', text: 'Following the river has brought her to a small discovery she would have missed on the main road.' }], media: media('square'), actions: [{ id: 'home', label: 'Head home with a new story', target: 'evening' }] },
  evening: { id: 'evening', step: 5, title: 'A small beginning', text: 'Back in her apartment, Jessica sets the borrowed book on the windowsill. The boxes can wait a moment. This morning, the city was just an address. Now it holds a place she wants to return to. That feels like a beginning.', media: media('evening'), actions: [{ id: 'finish', label: 'Finish the free chapter', target: 'demo' }] },
  demo: { id: 'demo', step: 5, kind: 'demo', title: 'There is more to her story', text: 'You have reached the end of the free fragment. This is a demonstration of a future subscription screen. Try one extra scene to see how the story could continue.', media: media('evening'), actions: [{ id: 'preview', label: 'Preview continuation', target: 'tomorrow' }] },
  tomorrow: { id: 'tomorrow', step: 6, kind: 'preview', title: 'A reason to go back', text: 'The next morning, Jessica chooses a favorite book from an open box. She slips a note between its pages: “For someone finding their feet.” Then she heads toward the square, a little more certain of the way. The rest of her story is still unwritten.', media: { type: 'video', src: '/media/jessica-walk.mp4', poster: '/media/jessica-walk-poster.jpg', alt: 'Jessica on a tree-lined path — video preview', caption: 'Jessica · Video preview' }, actions: [] },
};
