import {Router,type Request,type Response} from 'express';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import type {Pool,PoolConnection,RowDataPacket} from 'mysql2/promise';
import {advance,decodeProgress,initialProgress,type Progress} from '../src/progress.ts';
import {storyFromDb} from './content.ts';
import {linearScenes,nextSceneId} from '../src/linear.ts';
import {readerEvents,recordEvent} from './analytics.ts';

const guestCookie='jessica_guest';
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
type Owner={column:'user_id'|'guest_id';id:string};
type Db=Pool|PoolConnection;
type Session=(req:Request)=>Promise<{id:string;role:string}|null>;
type Preview={id:string;title:string;description:string;media:unknown;keyCost?:number};
type ReadingState={mode:'unstarted'|'active'|'awaiting'|'complete';heroineId:string;chapterId?:string;chapterTitle?:string;progress?:Progress;version?:number;lastCompletedChapterId?:string;finalPollId?:number|null;chapterCost?:number;chapterUnlocked?:boolean;guestFree?:boolean;completionPreview?:{nextChapter:Preview|null;stories:Preview[]}};

export async function guestIdentity(pool:Db,req:Request):Promise<string|null>{
 const token=req.cookies?.[guestCookie];
 if(typeof token!=='string'||! /^[a-f0-9]{64}$/.test(token))return null;
 const [rows]=await pool.execute<RowDataPacket[]>('SELECT id FROM guest_sessions WHERE token_hash=? AND expires_at>UTC_TIMESTAMP(3)',[hash(token)]);
 return rows[0]?.id??null;
}

export async function transferGuest(pool:Db,req:Request,userId:string){
 const guestId=await guestIdentity(pool,req);if(!guestId)return {guestId:null,progress:0,polls:0};
 const [progressResult]=await pool.execute<any>('INSERT IGNORE INTO progress(user_id,heroine_id,chapter_id,story_revision,scene_id,completed_scenes,choices,decisions,save_version,completed_at,updated_at) SELECT ?,heroine_id,chapter_id,story_revision,scene_id,completed_scenes,choices,decisions,save_version,completed_at,updated_at FROM progress WHERE guest_id=?',[userId,guestId]);
 const [pollResult]=await pool.execute<any>('INSERT IGNORE INTO poll_progress(poll_id,user_id,status,first_seen_at,updated_at) SELECT poll_id,?,status,first_seen_at,updated_at FROM poll_progress WHERE guest_id=?',[userId,guestId]);
 if(progressResult.affectedRows||pollResult.affectedRows)await recordEvent(pool,'guest_progress_transferred',{userId,guestId},{source:'registration'});
 return {guestId,progress:Number(progressResult.affectedRows),polls:Number(pollResult.affectedRows)};
}

export function readingRouter(pool:Pool,session:Session,production=false){
 const router=Router();
 async function owner(req:Request):Promise<Owner|null>{const user=await session(req);if(user)return {column:'user_id',id:user.id};const guestId=await guestIdentity(pool,req);return guestId?{column:'guest_id',id:guestId}:null;}
 async function requireOwner(req:Request,res:Response):Promise<Owner|null>{const result=await owner(req);if(!result)res.status(401).json({error:'Reading session unavailable. Retry.'});return result;}
 async function lock(c:PoolConnection,who:Owner){await c.execute(`SELECT id FROM ${who.column==='user_id'?'users':'guest_sessions'} WHERE id=? FOR UPDATE`,[who.id]);}
 async function completionPreview(db:Db,heroineId:string,chapterId:string){
  const [nextRows]=await db.execute<RowDataPacket[]>("SELECT c.id,c.title,c.description,c.key_cost,h.media FROM chapters current JOIN heroines h ON h.id=current.heroine_id JOIN chapters c ON c.heroine_id=current.heroine_id AND (c.display_order>current.display_order OR c.display_order=current.display_order AND c.id>current.id) WHERE current.id=? AND c.archived=FALSE AND c.published_revision IS NOT NULL ORDER BY c.display_order,c.id LIMIT 1",[chapterId]);
  const next=nextRows[0];
  const [stories]=await db.execute<RowDataPacket[]>("SELECT h.id,h.name AS title,h.description,h.media FROM heroines h WHERE h.archived=FALSE AND h.id<>? AND EXISTS(SELECT 1 FROM chapters c WHERE c.heroine_id=h.id AND c.archived=FALSE AND c.published_revision IS NOT NULL) ORDER BY h.name LIMIT 3",[heroineId]);
  return {nextChapter:next?{id:String(next.id),title:String(next.title),description:String(next.description),media:next.media,keyCost:Number(next.key_cost)}:null,stories:stories.map(row=>({id:String(row.id),title:String(row.title),description:String(row.description),media:row.media}))};
 }
 async function state(db:Db,who:Owner,heroineId:string):Promise<ReadingState>{
  const guest=who.column==='guest_id';
  const [chapters]=await db.execute<RowDataPacket[]>(`SELECT c.id,c.title,c.key_cost,c.guest_free,${guest?'c.guest_free':'(c.key_cost=0 OR EXISTS(SELECT 1 FROM chapter_unlocks u WHERE u.user_id=? AND u.chapter_id=c.id))'} AS unlocked FROM chapters c WHERE c.heroine_id=? AND c.archived=FALSE AND c.published_revision IS NOT NULL ${guest?'AND c.guest_free=TRUE':''} ORDER BY c.display_order,c.id`,guest?[heroineId]:[who.id,heroineId]);
  const [rows]=await db.execute<RowDataPacket[]>(`SELECT p.*,c.title FROM progress p JOIN chapters c ON c.id=p.chapter_id WHERE p.${who.column}=? AND p.heroine_id=? ${guest?'AND c.guest_free=TRUE':''} ORDER BY p.updated_at DESC,p.id DESC`,[who.id,heroineId]);
  const active=rows[0]?.completed_at===null?rows[0]:undefined;
  if(active){const story=await storyFromDb(db,active.chapter_id,active.story_revision,true);const progress=story?decodeProgress(JSON.stringify({revision:active.story_revision,sceneId:active.scene_id,choices:active.choices,decisions:active.decisions}),story):null;if(progress)return {mode:'active',heroineId,chapterId:active.chapter_id,chapterTitle:active.title,progress,version:active.save_version,chapterCost:0,chapterUnlocked:true,guestFree:!!chapters.find(c=>c.id===active.chapter_id)?.guest_free};throw Error('Saved chapter version is unavailable. Your path has not been changed.');}
  const completed=new Set(rows.map(row=>row.chapter_id));
  const recent=rows.find(row=>row.completed_at!==null),recentStory=recent?await storyFromDb(db,recent.chapter_id,recent.story_revision,true):null;
  const completion=recent?{lastCompletedChapterId:String(recent.chapter_id),finalPollId:recentStory?.chapter.finalPollId??null}:{};
  const next=chapters.find(chapter=>!completed.has(chapter.id));
  if(next)return {mode:completed.size?'awaiting':'unstarted',heroineId,chapterId:next.id,chapterTitle:next.title,chapterCost:Number(next.key_cost),chapterUnlocked:!!next.unlocked,guestFree:!!next.guest_free,...completion};
  return {mode:'complete',heroineId,...completion,...(guest&&recent?{completionPreview:await completionPreview(db,heroineId,String(recent.chapter_id))}:{})};
 }
 async function allStates(who:Owner){const guest=who.column==='guest_id';const [heroes]=await pool.query<RowDataPacket[]>(`SELECT DISTINCT h.id FROM heroines h JOIN chapters c ON c.heroine_id=h.id WHERE h.archived=FALSE AND c.archived=FALSE AND c.published_revision IS NOT NULL ${guest?'AND c.guest_free=TRUE':''}`);const result:Record<string,ReadingState>={};for(const hero of heroes)result[hero.id]=await state(pool,who,hero.id);return result;}
 router.post('/session',async(req,res)=>{if(await session(req)){res.json({ok:true});return;}if(await guestIdentity(pool,req)){res.json({ok:true});return;}const token=randomBytes(32).toString('hex'),id=randomUUID();await pool.execute('INSERT INTO guest_sessions(id,token_hash,expires_at) VALUES(?,?,?)',[id,hash(token),new Date(Date.now()+30*86400000)]);res.cookie(guestCookie,token,{httpOnly:true,secure:production,sameSite:'lax',path:'/api',maxAge:30*86400000});res.json({ok:true});});
 router.get('/state',async(req,res)=>{const who=await requireOwner(req,res);if(who)res.json({stories:await allStates(who)});});
 router.post('/open',async(req,res)=>{
  const who=await requireOwner(req,res);if(!who)return;const heroineId=req.body?.heroineId;if(typeof heroineId!=='string'||! /^[a-z0-9][a-z0-9-]{0,63}$/.test(heroineId)){res.status(400).json({error:'Choose a story.'});return;}
  const c=await pool.getConnection();try{await c.beginTransaction();await lock(c,who);let next=await state(c,who,heroineId);
   if(next.mode==='unstarted'||next.mode==='awaiting'){if(!next.chapterUnlocked){res.status(402).json({...next,error:`This chapter requires ${next.chapterCost} ${next.chapterCost===1?'Key':'Keys'}.`});return;}const story=await storyFromDb(c,next.chapterId!);if(!story){res.status(409).json({error:'Chapter is unavailable.'});return;}const progress=initialProgress(story);await c.execute(`INSERT INTO progress(${who.column},heroine_id,chapter_id,story_revision,scene_id,completed_scenes,choices,decisions,save_version) VALUES(?,?,?,?,?,JSON_ARRAY(),?,?,1)`,[who.id,heroineId,story.chapter.id,progress.revision,progress.sceneId,JSON.stringify(progress.choices),JSON.stringify(progress.decisions)]);if(who.column==='guest_id')await recordEvent(c,'guest_chapter_started',{guestId:who.id},{heroineId,chapterId:story.chapter.id,sceneId:progress.sceneId});next=await state(c,who,heroineId);}
   await c.commit();res.json(next);
  }catch(e){await c.rollback();throw e;}finally{await c.rollback();c.release();}
 });
 router.post('/unlock',async(req,res)=>{
  const user=await session(req);if(!user){res.status(401).json({error:'Create a profile or sign in to open paid chapters.'});return;}const {heroineId,chapterId}=req.body??{};if(typeof heroineId!=='string'||typeof chapterId!=='string'){res.status(400).json({error:'Choose a chapter.'});return;}
   const who:Owner={column:'user_id',id:user.id},c=await pool.getConnection();try{await c.beginTransaction();await lock(c,who);const current=await state(c,who,heroineId);if(!['unstarted','awaiting'].includes(current.mode)||current.chapterId!==chapterId){res.status(409).json({error:'Open chapters in story order.'});return;}const [rows]=await c.execute<RowDataPacket[]>('SELECT key_balance FROM users WHERE id=? FOR UPDATE',[user.id]);if(current.chapterUnlocked){await c.commit();res.json({keyBalance:Number(rows[0].key_balance),state:current,alreadyUnlocked:true});return;}const cost=current.chapterCost??0,before=Number(rows[0].key_balance);if(before<cost){res.status(402).json({error:'You do not have enough Keys.',keyBalance:before,required:cost});return;}await c.execute('INSERT INTO chapter_unlocks(user_id,chapter_id,key_cost) VALUES(?,?,?)',[user.id,chapterId,cost]);await c.execute('UPDATE users SET key_balance=key_balance-? WHERE id=?',[cost,user.id]);await c.execute("INSERT INTO key_transactions(id,user_id,admin_id,chapter_id,operation,balance_before,amount_delta,balance_after,reason,idempotency_key) VALUES(?,?,NULL,?,'chapter_unlock',?,?,?,?,?)",[randomUUID(),user.id,chapterId,before,-cost,before-cost,`Opened chapter: ${current.chapterTitle??chapterId}`,randomUUID()]);const next=await state(c,who,heroineId);await c.commit();res.json({keyBalance:before-cost,state:next,alreadyUnlocked:false});
  }catch(e){await c.rollback();throw e;}finally{await c.rollback();c.release();}
 });
 router.get('/chapter/:id',async(req,res)=>{const who=await requireOwner(req,res);if(!who)return;const [rows]=await pool.execute<RowDataPacket[]>(`SELECT p.heroine_id,p.story_revision,p.completed_at,c.guest_free FROM progress p JOIN chapters c ON c.id=p.chapter_id WHERE p.${who.column}=? AND p.chapter_id=?`,[who.id,req.params.id]);if(!rows[0]||rows[0].completed_at!==null||who.column==='guest_id'&&!rows[0].guest_free){res.status(403).json({error:'Open the current chapter from Stories.'});return;}const current=await state(pool,who,rows[0].heroine_id);if(current.mode!=='active'||current.chapterId!==req.params.id){res.status(403).json({error:'Only the active chapter can be read.'});return;}const story=await storyFromDb(pool,req.params.id,rows[0].story_revision,true);if(!story){res.status(404).json({error:'Saved chapter version unavailable.'});return;}res.json(story);});
 router.post('/advance',async(req,res)=>{
  const who=await requireOwner(req,res);if(!who)return;const {chapterId,actionId,version}=req.body??{};if(typeof chapterId!=='string'||typeof actionId!=='string'||!Number.isSafeInteger(version)){res.status(400).json({error:'Invalid reading action.'});return;}const c=await pool.getConnection();try{await c.beginTransaction();await lock(c,who);const [rows]=await c.execute<RowDataPacket[]>(`SELECT * FROM progress WHERE ${who.column}=? AND chapter_id=? FOR UPDATE`,[who.id,chapterId]);const row=rows[0];if(!row||row.completed_at!==null){res.status(403).json({error:'Chapter is not active.'});return;}const current=await state(c,who,row.heroine_id);if(current.mode!=='active'||current.chapterId!==chapterId){res.status(403).json({error:'Only the active chapter can advance.'});return;}if(row.save_version!==version){res.status(409).json({error:'Path changed in another tab. Reload the confirmed state.'});return;}const story=await storyFromDb(c,chapterId,row.story_revision,true),progress=current.progress!;if(actionId!=='next'||!story||!nextSceneId(story,progress.sceneId)){res.status(400).json({error:'Next scene is unavailable.'});return;}const next=advance(progress,actionId,story!);const completed=Array.isArray(row.completed_scenes)?row.completed_scenes:typeof row.completed_scenes==='string'?JSON.parse(row.completed_scenes):[];if(!completed.includes(progress.sceneId))completed.push(progress.sceneId);await c.execute('UPDATE progress SET scene_id=?,completed_scenes=?,choices=?,decisions=?,save_version=save_version+1 WHERE id=?',[next.sceneId,JSON.stringify(completed),JSON.stringify(next.choices),JSON.stringify(next.decisions),row.id]);await c.commit();res.json({...current,progress:next,version:version+1});
  }catch(e){await c.rollback();throw e;}finally{await c.rollback();c.release();}
 });
 router.post('/finish',async(req,res)=>{
  const who=await requireOwner(req,res);if(!who)return;const chapterId=req.body?.chapterId;if(typeof chapterId!=='string'){res.status(400).json({error:'Choose a chapter.'});return;}const c=await pool.getConnection();try{await c.beginTransaction();await lock(c,who);const [rows]=await c.execute<RowDataPacket[]>(`SELECT p.*,c.guest_free FROM progress p JOIN chapters c ON c.id=p.chapter_id WHERE p.${who.column}=? AND p.chapter_id=? FOR UPDATE`,[who.id,chapterId]);const row=rows[0];if(!row){res.status(403).json({error:'Chapter was not opened.'});return;}if(row.completed_at===null){const current=await state(c,who,row.heroine_id);if(current.mode!=='active'||current.chapterId!==chapterId){res.status(403).json({error:'Only the active chapter can finish.'});return;}const story=await storyFromDb(c,chapterId,row.story_revision,true);if(!story?.scenes[current.progress!.sceneId]||nextSceneId(story,current.progress!.sceneId)){res.status(409).json({error:'Reach the final scene before finishing.'});return;}const completed=Array.isArray(row.completed_scenes)?row.completed_scenes:typeof row.completed_scenes==='string'?JSON.parse(row.completed_scenes):[];if(!completed.includes(current.progress!.sceneId))completed.push(current.progress!.sceneId);await c.execute('UPDATE progress SET scene_id=?,completed_scenes=?,choices=?,decisions=?,completed_at=UTC_TIMESTAMP(3),save_version=save_version+1 WHERE id=?',[current.progress!.sceneId,JSON.stringify(completed),JSON.stringify(current.progress!.choices),JSON.stringify(current.progress!.decisions),row.id]);if(row.guest_free)await recordEvent(c,'first_chapter_completed',who.column==='user_id'?{userId:who.id}:{guestId:who.id},{heroineId:row.heroine_id,chapterId,sceneId:current.progress!.sceneId});}const next=await state(c,who,row.heroine_id);await c.commit();res.json({completedChapterId:chapterId,state:next});
  }catch(e){await c.rollback();throw e;}finally{await c.rollback();c.release();}
 });
 router.post('/event',async(req,res)=>{const who=await requireOwner(req,res);if(!who)return;const {type,heroineId,chapterId,sceneId,pollId,deviceType,source}=req.body??{};if(typeof type!=='string'||!readerEvents.has(type)){res.status(400).json({error:'Unknown event.'});return;}const validId=(v:unknown)=>v==null||typeof v==='string'&&v.length<=64;if(!validId(heroineId)||!validId(chapterId)||!validId(sceneId)||pollId!=null&&!Number.isSafeInteger(pollId)){res.status(400).json({error:'Invalid event details.'});return;}await recordEvent(pool,type,who.column==='user_id'?{userId:who.id}:{guestId:who.id},{heroineId,chapterId,sceneId,pollId,deviceType,source});res.json({ok:true});});
 router.post('/import',async(req,res)=>{
  const who=await requireOwner(req,res);if(!who)return;const {chapterId,progress}=req.body??{};if(typeof chapterId!=='string'||!progress||typeof progress!=='object'){res.status(400).json({error:'Invalid saved path.'});return;}const story=await storyFromDb(pool,chapterId,progress.revision,true),valid=story?decodeProgress(JSON.stringify(progress),story):null;if(!valid){res.status(400).json({error:'Saved path is unavailable.'});return;}const c=await pool.getConnection();try{await c.beginTransaction();await lock(c,who);const [first]=await c.execute<RowDataPacket[]>(`SELECT id FROM chapters WHERE heroine_id=? AND archived=FALSE AND published_revision IS NOT NULL ${who.column==='guest_id'?'AND guest_free=TRUE':''} ORDER BY display_order,id LIMIT 1`,[story!.chapter.heroineId]);const [existing]=await c.execute<RowDataPacket[]>(`SELECT id FROM progress WHERE ${who.column}=? AND heroine_id=?`,[who.id,story!.chapter.heroineId]);if(existing.length||first[0]?.id!==chapterId){res.status(409).json({error:'A server path already exists or this is not the first available chapter.'});return;}const sequence=linearScenes(story!),at=sequence.findIndex(scene=>scene.id===valid.sceneId),completed=sequence.slice(0,Math.max(0,at)).map(scene=>scene.id);await c.execute(`INSERT INTO progress(${who.column},heroine_id,chapter_id,story_revision,scene_id,completed_scenes,choices,decisions,save_version) VALUES(?,?,?,?,?,?,?,?,1)`,[who.id,story!.chapter.heroineId,chapterId,valid.revision,valid.sceneId,JSON.stringify(completed),JSON.stringify(valid.choices),JSON.stringify(valid.decisions)]);await c.commit();res.json({state:await state(pool,who,story!.chapter.heroineId)});
  }catch(e){await c.rollback();throw e;}finally{await c.rollback();c.release();}
 });
 return router;
}
