import { useEffect, useRef, useState } from 'react';
export function Account({ reader, onBilling, registerSignal=0,loginSignal=0 }: { reader: ReturnType<typeof import('./useReader').useReader>; onBilling: () => void; registerSignal?:number;loginSignal?:number }) {
 const [open,setOpen]=useState(false),[mode,setMode]=useState<'login'|'register'>('login'),[error,setError]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
 useEffect(()=>{if(registerSignal>0&&!reader.user){setMode('register');setError('');setOpen(true);}},[registerSignal,reader.user]);
 useEffect(()=>{if(loginSignal>0&&!reader.user){setMode('login');setError('');setOpen(true);}},[loginSignal,reader.user]);
 const balance = reader.user?.keyBalance;
 const hasBalance = typeof balance==='number' && Number.isSafeInteger(balance) && balance>=0;
 return <><div className="account-controls">{reader.user?<><button type="button" className="keys-control" onClick={onBilling} aria-label="Add keys" title="Add keys"><svg className="keys-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><circle cx="6.5" cy="10" r="3.5"/><path d="M10 10h11M16.5 10v4M20 10v4"/></svg><span>Keys</span><span className="keys-balance" aria-hidden="true">{hasBalance?balance:'—'}</span></button><span className="account-email" title={reader.user.email}>{reader.user.email}</span><button className="text-button" disabled={reader.busy} onClick={()=>void reader.logout()}>Sign out</button></>:<button className="text-button" disabled={reader.busy} onClick={()=>{setMode('login');setOpen(true);setError('');}}>Sign in</button>}</div>
 <dialog ref={dialog} onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} aria-labelledby="account-title"><h2 id="account-title">{mode==='login'?'Welcome back':'Create an account'}</h2><p>Keep your story progress across devices.</p><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setError('');try{await reader.authenticate(mode,String(data.get('email')),String(data.get('password')));form.reset();setOpen(false);}catch(err){setError(err instanceof Error?err.message:'Unable to sign in.');}}}>
 <label>Email<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Password<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='register'?6:undefined} maxLength={128}/></label>{mode==='register'&&<p className="small-note">Password must be at least 6 characters long.</p>}{error&&<p role="alert" className="warning">{error}</p>}<div className="actions"><button className="primary" disabled={reader.busy}>{reader.busy?'Please wait…':mode==='login'?'Sign in':'Register'}</button><button type="button" className="secondary" disabled={reader.busy} onClick={()=>{setMode(mode==='login'?'register':'login');setError('');}}>{mode==='login'?'Create an account':'I already have an account'}</button><button type="button" className="text-button" onClick={()=>setOpen(false)}>Close</button></div></form></dialog></>;
}

