import {useEffect,useRef,useState} from 'react';
import {api} from './api';
import {money,type BillingLocale,type BillingPlan} from './billingPlans';
import {PageMeta} from './PublicSite';

type Context={source:string;heroineId?:string;chapterId?:string;returnTo?:string};
const copy={title:'Choose your Keys',subtitle:'One key unlocks the next locked chapter in any story you choose.',keys:(n:number)=>`${n} Keys`,perKey:(p:BillingPlan)=>p.id==='economy'?'≈ $0.86 per Key':'$1 per Key',saving:(n:number)=>`Save ${n}%`,choose:'Choose',checkout:'Continue to payment',soon:'Key purchases are coming soon',message:'Sorry, Key purchases are not available yet. Storymera is in a test launch. We are preparing new chapters and will add payment soon.\n\nThank you for your choice — it helps us understand which offers interest readers most.',stories:'Return to Stories',close:'Close',loading:'Loading plans…'};

export function BillingPage({context,onReturn}:{context:Context;onReturn:(target:string)=>void}){
 const locale:BillingLocale='en',t=copy;
 const [plans,setPlans]=useState<BillingPlan[]>([]),[selected,setSelected]=useState<string|null>(null),[processing,setProcessing]=useState(false),[modal,setModal]=useState(false),[error,setError]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),checkout=useRef<HTMLButtonElement>(null);
 const details={source:context.source,heroineId:context.heroineId,chapterId:context.chapterId};
 const track=async(type:string,planId?:string)=>{try{await api('/billing/events','POST',{type,planId,...details});}catch{/* The honest unavailable-payment message must still be shown. */}};
 useEffect(()=>{let alive=true;document.documentElement.lang=locale;void api('/billing/plans').then(result=>{if(alive)setPlans(result.plans);}).catch(e=>{if(alive)setError(e instanceof Error?e.message:'Plans unavailable.');});void track('plans_page_viewed');return()=>{alive=false;};},[]);
 useEffect(()=>{if(modal){dialog.current?.showModal();void track('payment_unavailable_shown',selected??undefined);}else if(dialog.current?.open){dialog.current.close();checkout.current?.focus();}},[modal]);
 const choose=(id:string)=>{if(selected===id)return;setSelected(id);void track('plan_selected',id);};
 const plan=plans.find(item=>item.id===selected);
 const pay=async()=>{if(!plan||processing)return;setProcessing(true);await track('checkout_clicked',plan.id);setModal(true);setProcessing(false);};
 const leave=async()=>{await track('returned_to_stories',selected??undefined);onReturn(context.returnTo??'/');};
 return <><PageMeta path="/billing"/><section className="billing-page" aria-labelledby="billing-title"><header><h1 id="billing-title">{t.title}</h1><p>{t.subtitle}</p></header>{error?<p role="alert" className="warning">{error}</p>:!plans.length?<p>{t.loading}</p>:<><div className="billing-plans" role="radiogroup" aria-label={t.title}>{plans.map(item=>{const checked=item.id===selected;return <article key={item.id} className={`billing-plan${checked?' selected':''}`} role="radio" aria-checked={checked} tabIndex={0} onClick={()=>choose(item.id)} onKeyDown={event=>{if(event.key===' '||event.key==='Enter'){event.preventDefault();choose(item.id);}}}><div><input type="radio" name="key-plan" checked={checked} onClick={event=>event.stopPropagation()} onChange={()=>choose(item.id)} aria-label={`${item.name[locale]}, ${t.keys(item.keys)}, ${money(item.priceMinor,item.currency,locale)}`}/>{item.savingPercent>0&&<span className="plan-saving">{t.saving(item.savingPercent)}</span>}</div><h2>{item.name[locale]}</h2><strong className="plan-keys">{t.keys(item.keys)}</strong><span className="plan-price">{money(item.priceMinor,item.currency,locale)}</span><small>{t.perKey(item)}</small><button type="button" className="secondary" onClick={event=>{event.stopPropagation();choose(item.id);}}>{t.choose}</button></article>;})}</div><button ref={checkout} type="button" className="primary billing-checkout" disabled={!plan||processing} onClick={()=>void pay()}>{plan?`${t.checkout} — ${money(plan.priceMinor,plan.currency,locale)}`:t.checkout}</button></>}</section><dialog ref={dialog} className="payment-unavailable" aria-labelledby="payment-unavailable-title" onCancel={()=>setModal(false)} onClose={()=>setModal(false)}><h2 id="payment-unavailable-title">{t.soon}</h2>{t.message.split('\n\n').map(part=><p key={part}>{part}</p>)}<div className="actions"><button className="primary" autoFocus onClick={()=>void leave()}>{t.stories}</button><button className="text-button" onClick={()=>setModal(false)}>{t.close}</button></div></dialog></>;
}
