import {useEffect,useState} from 'react';
import {api} from './api';
import {money,type BillingPlan} from './billingPlans';

type Metric={total:number;unique:number};
type Stats={period:string;summary:{views:Metric;selections:Metric;checkouts:Metric;viewToSelection:number;viewToCheckout:number;selectionToCheckout:number;planSwitches:number;firstSelections:Record<string,number>;lastSelections:Record<string,number>};plans:(BillingPlan&{selections:number;uniqueSelections:number;checkouts:number;uniqueCheckouts:number})[]};
export function BillingStats(){
 const [period,setPeriod]=useState('all'),[data,setData]=useState<Stats|null>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setData(null);setError('');void api('/admin/billing/stats?period='+period).then(value=>{if(alive)setData(value);}).catch(e=>{if(alive)setError(e instanceof Error?e.message:'Statistics unavailable.');});return()=>{alive=false;};},[period]);
 return <section className="admin-panel billing-stats"><div className="admin-heading"><div><h2>Key plan statistics</h2><p>Purchase intent only. No payments or Key credits are created.</p></div><div className="admin-tabs" role="group" aria-label="Period">{[['all','All time'],['7','Last 7 days'],['30','Last 30 days']].map(([id,label])=><button key={id} aria-pressed={period===id} onClick={()=>setPeriod(id)}>{label}</button>)}</div></div>{error&&<p className="warning" role="alert">{error}</p>}{!data&&!error?<p>Loading statistics…</p>:data&&<><div className="billing-stat-cards"><article><strong>{data.summary.views.total}</strong><span>Page views</span><small>{data.summary.views.unique} unique users</small></article><article><strong>{data.summary.selections.total}</strong><span>Plan selections</span><small>{data.summary.selections.unique} unique users</small></article><article><strong>{data.summary.checkouts.total}</strong><span>Checkout clicks</span><small>{data.summary.checkouts.unique} unique users</small></article></div><div className="billing-conversions"><span>View → selection <strong>{data.summary.viewToSelection}%</strong></span><span>View → checkout <strong>{data.summary.viewToCheckout}%</strong></span><span>Selection → checkout <strong>{data.summary.selectionToCheckout}%</strong></span><span>Plan changes <strong>{data.summary.planSwitches}</strong></span></div><div className="admin-table-wrap"><table><thead><tr><th>Plan</th><th>Offer</th><th>Selections</th><th>Unique selections</th><th>Checkout clicks</th><th>Unique checkout users</th><th>First / last selection</th></tr></thead><tbody>{data.plans.map(plan=><tr key={plan.id}><th>{plan.name.en}</th><td>{plan.keys} Keys · {money(plan.priceMinor,plan.currency)}</td><td>{plan.selections}</td><td>{plan.uniqueSelections}</td><td>{plan.checkouts}</td><td>{plan.uniqueCheckouts}</td><td>{data.summary.firstSelections[plan.id]??0} / {data.summary.lastSelections[plan.id]??0}</td></tr>)}</tbody></table></div></>}</section>;
}
