import {useEffect,useState} from 'react';
import {api} from './api';

export type LibraryAsset={id:string;mime:string;original_name:string;size_bytes:number;poster_src?:string|null};
type Job={key:string;file:File;state:'waiting'|'uploading'|'done'|'failed';error?:string};
type Check={id:string;name:string;status:'eligible'|'blocked'|'missing'|'deleted'|'error';uses:string[];archivedUses:string[];error?:string};
type Trashed={id:string;original_name:string;mime:string;deleted_at:string};
const maxBatch=10,parallel=2;
export function MediaLibrary({assets,onUpload,onRefresh}:{assets:LibraryAsset[];onUpload:(file:File)=>Promise<unknown>;onRefresh:()=>Promise<void>}){
 const [filter,setFilter]=useState<'all'|'image'|'video'>('all'),[selected,setSelected]=useState<Set<string>>(new Set());
 const [jobs,setJobs]=useState<Job[]>([]),[plan,setPlan]=useState<Check[]|null>(null),[report,setReport]=useState<Check[]|null>(null),[trash,setTrash]=useState<Trashed[]>([]),[error,setError]=useState(''),[working,setWorking]=useState(false),[uploadOpen,setUploadOpen]=useState(false);
 const shown=assets.filter(a=>filter==='all'||a.mime.startsWith(filter+'/'));
 const count=(kind:string)=>assets.filter(a=>a.mime.startsWith(kind+'/')).length;
 const uploadSummary=([['uploading','uploading'],['waiting','queued'],['done','uploaded'],['failed','failed']] as const).map(([state,label])=>{const n=jobs.filter(j=>j.state===state).length;return n?`${n} ${label}`:'';}).filter(Boolean).join(' · ');
 useEffect(()=>{setSelected(new Set());setPlan(null);},[filter]);
 async function loadTrash(){const r=await api('/admin/media/trash');setTrash(r);}
 useEffect(()=>{void loadTrash().catch(()=>{});},[]);
 async function run(files:File[],retryKey?:string){
  if(!files.length)return;setError('');setWorking(true);
  const batch=files.slice(0,maxBatch).map(file=>({key:retryKey??crypto.randomUUID(),file,state:'waiting' as const}));
  setJobs(previous=>retryKey?previous.map(j=>j.key===retryKey?batch[0]:j):[...previous,...batch]);
  if(files.length>maxBatch)setError(`Only the first ${maxBatch} images were queued. Select the remaining files in another batch.`);
  let cursor=0;const work=async()=>{while(cursor<batch.length){const job=batch[cursor++];setJobs(old=>old.map(j=>j.key===job.key?{...j,state:'uploading'}:j));try{await onUpload(job.file);setJobs(old=>old.map(j=>j.key===job.key?{...j,state:'done',error:undefined}:j));}catch(e){setJobs(old=>old.map(j=>j.key===job.key?{...j,state:'failed',error:e instanceof Error?e.message:'Upload failed.'}:j));}}};
  await Promise.all(Array.from({length:Math.min(parallel,batch.length)},work));setWorking(false);
 }
 async function inspect(){setError('');try{const r=await api('/admin/media/inspect','POST',{ids:[...selected]});setPlan(r.files);setReport(null);}catch(e){setError(e instanceof Error?e.message:'Could not check files.');}}
 async function remove(){if(!plan)return;setWorking(true);setError('');try{const ids=plan.filter(x=>x.status==='eligible').map(x=>x.id);if(!ids.length)return;const r=await api('/admin/media/delete','POST',{ids});setReport([...plan.filter(x=>x.status!=='eligible'),...r.files]);setPlan(null);setSelected(new Set());await onRefresh();await loadTrash();}catch(e){setError(e instanceof Error?e.message:'Deletion failed.');}finally{setWorking(false);}}
 async function restore(id:string){setWorking(true);setError('');try{await api('/admin/media/restore','POST',{id});await onRefresh();await loadTrash();setReport(null);}catch(e){setError(e instanceof Error?e.message:'Restore failed.');}finally{setWorking(false);}}
 return <section className="admin-panel admin-media-library"><div className="media-library-heading"><h2>Media library</h2><div className="media-library-heading-actions">{!uploadOpen&&(uploadSummary||error)&&<span className="media-upload-summary" role="status">{[uploadSummary,error?'Upload needs attention':''].filter(Boolean).join(' · ')}</span>}<button type="button" aria-expanded={uploadOpen} aria-controls="media-upload-panel" onClick={()=>setUploadOpen(open=>!open)}>Upload files</button></div></div>
 <div id="media-upload-panel" className="media-upload-panel" hidden={!uploadOpen}><div className="media-upload-fields"><div className="media-upload-field"><label>Upload images<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple disabled={working} onChange={e=>{const files=[...e.target.files??[]];e.target.value='';void run(files);}}/></label><p>Up to 10 images per upload. JPEG, PNG, WebP or GIF; 12 MB each.</p></div><div className="media-upload-field"><label>Upload one video<input type="file" accept="video/mp4,video/webm" disabled={working} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run([file]);}}/></label><p>MP4 or WebM; 200 MB maximum. A poster is prepared when possible.</p></div></div>
 {!!jobs.length&&<div className="admin-upload-queue" role="status"><h3>Upload queue</h3>{jobs.map(j=><div className="admin-row" key={j.key}><div><strong>{j.file.name}</strong><p>{j.state==='waiting'?'Waiting':j.state==='uploading'?'Uploading…':j.state==='done'?'Uploaded':j.error}</p></div>{j.state==='failed'&&<button disabled={working} onClick={()=>void run([j.file],j.key)}>Retry failed</button>}</div>)}</div>}
 {error&&<p className="warning" role="alert">{error}</p>}</div>
 <div className="admin-tools admin-tabs media-filter-row" role="tablist" aria-label="Media type">{([['all','All',assets.length],['image','Images',count('image')],['video','Videos',count('video')]] as const).map(([key,label,n])=><button type="button" role="tab" aria-selected={filter===key} key={key} onClick={()=>setFilter(key)}>{label} ({n})</button>)}</div>
 <div className="admin-tools media-selection-row"><label className="check"><input type="checkbox" disabled={!shown.length} checked={shown.length>0&&shown.every(a=>selected.has(a.id))} onChange={e=>setSelected(e.target.checked?new Set(shown.map(a=>a.id)):new Set())}/>Select all shown</label><span>{selected.size} selected</span><button disabled={!selected.size||working} onClick={()=>void inspect()}>Delete selected</button></div>
 {shown.length===0?<p className="admin-empty-state">No {filter==='all'?'managed files':filter+' files'} yet.</p>:<div className="media-file-list">{shown.map(a=><article className="admin-row admin-media-row" key={a.id}><input aria-label={`Select ${a.original_name}`} type="checkbox" checked={selected.has(a.id)} onChange={e=>setSelected(previous=>{const next=new Set(previous);if(e.target.checked)next.add(a.id);else next.delete(a.id);return next;})}/>{a.mime.startsWith('image/')?<img className="admin-thumb" src={'/api/media/'+a.id} alt=""/>:a.poster_src?<img className="admin-thumb" src={a.poster_src} alt=""/>:<div className="admin-thumb admin-empty">No poster</div>}<div><h3>{a.original_name}</h3><p>{a.mime.startsWith('video/')?'Video':'Image'} · {(a.size_bytes/1024/1024).toFixed(1)} MB</p></div></article>)}</div>}
 {plan&&<div className="admin-panel admin-delete-review" role="alertdialog" aria-label="Review selected files"><h3>Review deletion</h3><p>Selected: {plan.length}. Eligible for recoverable trash: {plan.filter(x=>x.status==='eligible').length}. Protected by current content: {plan.filter(x=>x.status==='blocked').length}.</p>{plan.map(p=><div key={p.id}><strong>{p.name}</strong> — {p.status==='eligible'?'Can move to recoverable trash':p.status==='blocked'?'Protected by current content':'Unavailable'}{p.uses.length>0&&<><p>Current dependencies:</p><ul>{p.uses.map((u,i)=><li key={i}>{u}</li>)}</ul></>}{p.archivedUses?.length>0&&<><p>Archived version dependencies (kept available after trashing):</p><ul>{p.archivedUses.map((u,i)=><li key={i}>{u}</li>)}</ul></>}</div>)}<div className="admin-tools"><button disabled={working||!plan.some(x=>x.status==='eligible')} onClick={()=>void remove()}>Move eligible files to trash</button><button onClick={()=>setPlan(null)}>Cancel</button></div></div>}
 {report&&<div className="admin-panel" role="status"><h3>Deletion results</h3>{report.map(r=><p key={r.id}>{r.name}: {r.status}{r.error?' — '+r.error:''}</p>)}</div>}
 <details className="admin-trash"><summary>Recoverable trash ({trash.length})</summary><p>Files are hidden from the library. Historical chapter versions can still use their stable managed ID. Restore returns the file to the library.</p>{trash.map(t=><div className="admin-row" key={t.id}><div><strong>{t.original_name}</strong><p>{t.mime} · moved {new Date(t.deleted_at).toLocaleString()}</p></div><button disabled={working} onClick={()=>void restore(t.id)}>Restore</button></div>)}</details>
 </section>;
}
