import {useEffect,useState} from 'react';
import {api} from './api';
import {paths,type AdminRoute} from './adminRoutes';

type Option={id?:number|null;text:string;description:string;sortOrder?:number};
type Placement={chapterId:string;chapterTitle:string;sceneId:string|null;sceneTitle:string|null;versionStatus:string};
type Poll={id:number;adminTitle:string;question:string;description:string;type:'opinion'|'canonical';status:'draft'|'active'|'closed'|'implemented'|'archived';allowSkip:boolean;showResults:boolean;allowVoteChange:boolean;openAt:string|null;closeAt:string|null;canonicalOptionId:number|null;officialTotal:number|null;options:Option[];placements:Placement[];voteCount?:number;winnerLabel?:string|null};
type Stats=Omit<Poll,'options'>&{total:number;views:number;uniqueViewers:number;voters:number;conversion:number;changedVotes:number;firstVote:string|null;lastVote:string|null;options:(Option&{id:number;votes:number;percent:number})[]};
const blank=():Poll=>({id:0,adminTitle:'',question:'',description:'',type:'opinion',status:'draft',allowSkip:true,showResults:false,allowVoteChange:false,openAt:null,closeAt:null,canonicalOptionId:null,officialTotal:null,options:[{text:'',description:''},{text:'',description:''}],placements:[]});
const dateInput=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):'';
const dateOutput=(value:string)=>value?new Date(value).toISOString():null;
const placementLabel=(p:Placement)=>`${p.chapterTitle}${p.sceneTitle?' → '+p.sceneTitle:' → Final vote'} (${p.versionStatus})`;

export function PollAdmin({route,navigate}:{route:Extract<AdminRoute,{kind:'polls'|'poll-new'|'poll-edit'|'poll-stats'}>;navigate:(target:string)=>void}){
 const [items,setItems]=useState<Poll[]>([]),[poll,setPoll]=useState<Poll|null>(null),[stats,setStats]=useState<Stats|null>(null);
 const [search,setSearch]=useState(''),[typeFilter,setTypeFilter]=useState('all'),[statusFilter,setStatusFilter]=useState('all');
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false);
 useEffect(()=>{let live=true;setLoading(true);setError('');setNotice('');setDirty(false);setPoll(null);setStats(null);
  if(route.kind==='poll-new'){setPoll(blank());setLoading(false);return;}
  const path=route.kind==='polls'?'/admin/polls':route.kind==='poll-stats'?`/admin/polls/${route.pollId}/stats`:`/admin/polls/${route.pollId}`;
  void api(path).then(value=>{if(!live)return;if(route.kind==='polls')setItems(value);else if(route.kind==='poll-stats')setStats(value);else setPoll(value);setLoading(false);}).catch(e=>{if(live){setError(e instanceof Error?e.message:'Polls unavailable.');setLoading(false);}});
  return()=>{live=false;};
 },[route.kind,'pollId'in route?route.pollId:0]);
 useEffect(()=>{if(!dirty)return;const unload=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};addEventListener('beforeunload',unload);return()=>removeEventListener('beforeunload',unload);},[dirty]);
 function edit(change:(item:Poll)=>void){if(!poll)return;const next=structuredClone(poll);change(next);setPoll(next);setDirty(true);}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Request failed. Edits remain here.');}finally{setBusy(false);}}
 async function refresh(){setItems(await api('/admin/polls'));}
 const filtered=items.filter(item=>(typeFilter==='all'||item.type===typeFilter)&&(statusFilter==='all'||item.status===statusFilter)&&(`${item.id} ${item.adminTitle}`.toLowerCase().includes(search.toLowerCase())));
 const canEdit=poll&&['draft','active'].includes(poll.status);
 async function save(){if(!poll)return;const payload={...poll,openAt:poll.openAt,closeAt:poll.closeAt,options:poll.options.map(o=>({id:o.id??null,text:o.text,description:o.description}))};if(!poll.question.trim()&&poll.status==='active')throw Error('Question is required before activation.');if(poll.options.length<2||poll.options.some(o=>!o.text.trim()))throw Error('Add at least two non-empty options.');if(poll.openAt&&poll.closeAt&&new Date(poll.closeAt)<=new Date(poll.openAt))throw Error('Close time must be after open time.');
  if(route.kind==='poll-new'){const created=await api('/admin/polls','POST',payload);if(poll.status==='active')await api('/admin/polls/'+created.id,'PATCH',payload);setDirty(false);navigate(paths.pollEdit(created.id));}
  else{await api('/admin/polls/'+poll.id,'PATCH',payload);setPoll(await api('/admin/polls/'+poll.id));setDirty(false);setNotice('Poll saved.');}
 }
 const action=(label:string,fn:()=>Promise<void>)=><button disabled={busy} onClick={()=>void run(fn)}>{label}</button>;
 if(loading)return <section className="admin-panel" role="status">Loading polls…</section>;
 return <section className="admin-panel poll-admin"><div className="admin-heading"><h2>{route.kind==='polls'?'Polls':route.kind==='poll-new'?'New poll':route.kind==='poll-stats'?'Poll statistics':'Edit poll'}</h2>{route.kind==='polls'?<a className="admin-link primary" href={paths.pollNew} onClick={e=>{e.preventDefault();navigate(paths.pollNew);}}>Create poll</a>:<a className="admin-link" href={paths.polls} onClick={e=>{e.preventDefault();if(!dirty||confirm('Discard unsaved poll changes?'))navigate(paths.polls);}}>Back to polls</a>}</div>
  {error&&<p className="warning" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {route.kind==='polls'&&<><div className="poll-filters"><label>Search by ID or title<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Type<select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="all">All types</option><option value="opinion">Opinion</option><option value="canonical">Canonical</option></select></label><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All statuses</option>{['draft','active','closed','implemented','archived'].map(s=><option key={s} value={s}>{s}</option>)}</select></label></div><div className="poll-table-wrap"><table className="poll-table"><thead><tr><th>ID</th><th>Internal title</th><th>Type</th><th>Status</th><th>Placement</th><th>Votes</th><th>Winner</th><th>Actions</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td>#{item.id}</td><td>{item.adminTitle}</td><td>{item.type}</td><td>{item.status}</td><td>{item.placements.map(placementLabel).join('; ')||'Unattached'}</td><td>{item.voteCount??0}</td><td>{item.winnerLabel??'—'}</td><td><div className="admin-tools"><a href={paths.pollEdit(item.id)} onClick={e=>{e.preventDefault();navigate(paths.pollEdit(item.id));}}>Edit</a><a href={paths.pollStats(item.id)} onClick={e=>{e.preventDefault();navigate(paths.pollStats(item.id));}}>Statistics</a>{item.status==='active'&&action('Close',async()=>{if(!confirm('Close this poll and freeze its official results?'))return;const r=await api('/admin/polls/'+item.id+'/close','POST',{});await refresh();setNotice(r.tie?'Voting closed with a tie. Choose a winner manually.':'Voting closed.');})}</div></td></tr>)}</tbody></table></div></>}
  {(route.kind==='poll-new'||route.kind==='poll-edit')&&poll&&<div className="admin-editor"><p role="status">{dirty?'Unsaved changes':'Saved'} · {poll.status}</p>{poll.placements.length>0&&<p>Placement: {poll.placements.map(placementLabel).join('; ')}</p>}
   <label>Internal title<input maxLength={200} value={poll.adminTitle} disabled={!canEdit} onChange={e=>edit(p=>{p.adminTitle=e.target.value;})}/></label>
   <label>Question<input maxLength={500} value={poll.question} disabled={!canEdit} onChange={e=>edit(p=>{p.question=e.target.value;})}/></label>
   <label>Description<textarea value={poll.description} disabled={!canEdit} onChange={e=>edit(p=>{p.description=e.target.value;})}/></label>
   <label>Type<select value={poll.type} disabled={!canEdit||!!poll.voteCount} onChange={e=>edit(p=>{p.type=e.target.value as Poll['type'];})}><option value="opinion">Opinion</option><option value="canonical">Canonical</option></select></label>
   <label>Status<select value={poll.status} disabled={!canEdit||poll.status==='active'} onChange={e=>edit(p=>{p.status=e.target.value as Poll['status'];})}>{poll.status==='draft'&&<option value="draft">Draft</option>}<option value="active">Active</option>{!canEdit&&<option value={poll.status}>{poll.status}</option>}</select></label>
   <label className="check"><input type="checkbox" checked={poll.allowSkip} disabled={!canEdit} onChange={e=>edit(p=>{p.allowSkip=e.target.checked;})}/>Allow skip</label>
   <label className="check"><input type="checkbox" checked={poll.showResults} disabled={!canEdit} onChange={e=>edit(p=>{p.showResults=e.target.checked;})}/>Show results to readers</label>
   <label className="check"><input type="checkbox" checked={poll.allowVoteChange} disabled={!canEdit} onChange={e=>edit(p=>{p.allowVoteChange=e.target.checked;})}/>Allow vote changes while active</label>
   <div className="poll-dates"><label>Opens at<input type="datetime-local" value={dateInput(poll.openAt)} disabled={!canEdit} onChange={e=>edit(p=>{p.openAt=dateOutput(e.target.value);})}/></label><label>Closes at<input type="datetime-local" value={dateInput(poll.closeAt)} disabled={!canEdit} onChange={e=>edit(p=>{p.closeAt=dateOutput(e.target.value);})}/></label></div>
   <h3>Options</h3>{poll.options.map((option,index)=><fieldset key={option.id??'new-'+index}><legend>Option {index+1}{option.id?' · #'+option.id:''}</legend><label>Text<input maxLength={500} value={option.text} disabled={!canEdit||!!poll.voteCount} onChange={e=>edit(p=>{p.options[index].text=e.target.value;})}/></label><label>Description<textarea value={option.description} disabled={!canEdit||!!poll.voteCount} onChange={e=>edit(p=>{p.options[index].description=e.target.value;})}/></label><div className="admin-tools"><button disabled={!canEdit||index===0} onClick={()=>edit(p=>{[p.options[index-1],p.options[index]]=[p.options[index],p.options[index-1]];})}>Up</button><button disabled={!canEdit||index===poll.options.length-1} onClick={()=>edit(p=>{[p.options[index+1],p.options[index]]=[p.options[index],p.options[index+1]];})}>Down</button><button disabled={!canEdit||!!poll.voteCount||poll.options.length<=2} onClick={()=>edit(p=>{p.options.splice(index,1);})}>Remove</button></div></fieldset>)}
   {poll.voteCount? <p className="admin-help">Options with votes cannot be removed or reworded. Create a new poll for a major change.</p>:null}
   <div className="admin-tools"><button disabled={!canEdit} onClick={()=>edit(p=>{p.options.push({text:'',description:''});})}>Add option</button><button className="primary" disabled={!canEdit||busy||!dirty&&route.kind!=='poll-new'} onClick={()=>void run(save)}>{busy?'Saving…':'Save poll'}</button></div>
   {poll.id>0&&poll.status==='active'&&action('Close voting',async()=>{if(!confirm('Close voting and freeze the results?'))return;const r=await api('/admin/polls/'+poll.id+'/close','POST',{});setPoll(await api('/admin/polls/'+poll.id));setNotice(r.tie?'Voting closed with a tie. Choose a winner manually.':'Voting closed.');})}
   {['closed','implemented'].includes(poll.status)&&<><a className="admin-link" href={paths.pollStats(poll.id)} onClick={e=>{e.preventDefault();navigate(paths.pollStats(poll.id));}}>Statistics and winner</a>{action('Archive',async()=>{if(poll.placements.length&&!confirm('This poll is attached to a chapter or scene. Archive it anyway?'))return;await api('/admin/polls/'+poll.id+'/archive','POST',{confirmAttached:poll.placements.length>0});setPoll(await api('/admin/polls/'+poll.id));setNotice('Poll archived. Official results remain saved.');})}</>}
  </div>}
  {route.kind==='poll-stats'&&stats&&<div><h3>{stats.adminTitle}</h3><p>{stats.question}</p><p>Status: {stats.status} · Type: {stats.type} · Placement: {stats.placements.map(placementLabel).join('; ')||'Unattached'}</p><div className="poll-stats-grid"><div>Views <strong>{stats.views}</strong></div><div>Unique viewers <strong>{stats.uniqueViewers}</strong></div><div>Voters <strong>{stats.voters}</strong></div><div>Conversion <strong>{stats.conversion}%</strong></div><div>Changed votes <strong>{stats.changedVotes}</strong></div><div>First vote <strong>{stats.firstVote?new Date(stats.firstVote).toLocaleString():'—'}</strong></div><div>Last vote <strong>{stats.lastVote?new Date(stats.lastVote).toLocaleString():'—'}</strong></div><div>Official total <strong>{stats.officialTotal??'Not closed'}</strong></div></div><h3>Options</h3>{stats.options.map(option=><p key={option.id}>{option.text}: {option.votes} votes · {option.percent.toFixed(1)}% {stats.canonicalOptionId===option.id?'· Canonical':''}</p>)}<p>Current leader: {stats.options.filter(o=>o.votes===Math.max(...stats.options.map(x=>x.votes))).map(o=>o.text).join(', ')||'—'}</p>{stats.status==='closed'&&stats.type==='canonical'&&<label>Choose canonical winner<select value={stats.canonicalOptionId??''} onChange={e=>void run(async()=>{await api('/admin/polls/'+stats.id+'/canonical-option','POST',{optionId:Number(e.target.value)});setStats(await api('/admin/polls/'+stats.id+'/stats'));})}><option value="">Choose option…</option>{stats.options.map(o=><option key={o.id} value={o.id}>{o.text}</option>)}</select></label>}{stats.status==='closed'&&stats.canonicalOptionId&&action('Mark implemented',async()=>{await api('/admin/polls/'+stats.id+'/implemented','POST',{});setStats(await api('/admin/polls/'+stats.id+'/stats'));})}</div>}
 </section>;
}
