import {useEffect} from 'react';
import type {CatalogItem,Media} from './story-model';
import type {ReadingState} from './reading-model';
import {StoryMedia} from './StoryScene';
import {BRAND_LOGO,publicSiteUrl,SITE_NAME} from './siteConfig';
import {guestPrimaryCta} from './public-site-cta';

export type HomeStory={id:string;name:string;description:string;media:Media;publishedChapters:number;hasFreeChapter:boolean};
export type HomeData={stories:HomeStory[];stats:{publishedChapters:number;illustratedScenes:number;activePolls:number;firstChapterFree:boolean};contactEmail:string|null};

type Navigate=(path:string)=>void;
const descriptions:Record<string,string>={
 '/':'Illustrated stories with sequential chapters and reader votes that help shape what comes next.',
 '/about':'Learn how Storymera combines sequential fiction, illustrations, and reader voting.',
 '/how-it-works':'Learn how free first chapters, saved progress, Keys, and reader voting work in Storymera.',
 '/privacy':'Privacy information for guest progress, accounts, voting, and technical logs in Storymera.',
 '/terms':'Terms for accounts, saved reading progress, voting, Keys, and story access in Storymera.',
 '/contact':'Contact information for Storymera.',
};
const titles:Record<string,string>={'/':'Storymera — illustrated stories shaped by readers','/about':'About Storymera','/how-it-works':'How Storymera works','/privacy':'Privacy policy — Storymera','/terms':'Terms of use — Storymera','/contact':'Contact — Storymera','/billing':'Keys — Storymera'};

export function PageMeta({path,image}:{path:string;image?:string}){
 useEffect(()=>{const title=titles[path]??SITE_NAME,description=descriptions[path]??descriptions['/'],canonical=publicSiteUrl(path);document.title=title;document.documentElement.lang='en';
  const set=(selector:string,attribute:string,value:string)=>{let node=document.head.querySelector<HTMLMetaElement>(selector);if(!node){node=document.createElement(selector.startsWith('link')?'link':'meta') as HTMLMetaElement;document.head.append(node);}node.setAttribute(attribute,value);};
  set('meta[name="description"]','content',description);set('meta[name="robots"]','content',Object.hasOwn(titles,path)?'index,follow':'noindex,nofollow');set('meta[property="og:title"]','content',title);set('meta[property="og:description"]','content',description);set('meta[property="og:type"]','content','website');set('meta[property="og:url"]','content',canonical);set('meta[property="og:image"]','content',publicSiteUrl(image??BRAND_LOGO));set('link[rel="canonical"]','href',canonical);
 },[path,image]);return null;
}

function StoryFeatureCard({story,state,user,busy,publishedCount,actionLabel,onOpen,onRegister,onLogin,featured=false}:{story:CatalogItem;state?:ReadingState;user:boolean;busy:boolean;publishedCount:number;actionLabel:(state?:ReadingState)=>string;onOpen:(id:string,state?:ReadingState)=>void;onRegister:()=>void;onLogin:()=>void;featured?:boolean}){
 const available=!!state&&state.mode!=='complete',guestComplete=!user&&featured&&state?.mode==='complete',lastCompletedAt=story.chapters.findIndex(chapter=>chapter.id===state?.lastCompletedChapterId);const statusLabel=state?.mode==='active'?'In progress':state?.mode==='complete'?'Published · completed':state?.mode==='awaiting'?'Published · next chapter available':'Published';
 const guestAction=!user?guestPrimaryCta(state?.mode).primary:actionLabel(state);
 return <article className="heroine-card" id={featured?'featured-story':undefined}><div className="card-art"><StoryMedia media={story.media}/></div><div className="card-copy"><span className="story-status">{statusLabel}</span><h2>{story.name}<span className="coral">.</span></h2><p className="description">{story.description}</p>{guestComplete?<div className="guest-complete-cta"><strong>Chapter 1 completed</strong><p>Create a profile to continue Jessica’s story and keep your progress.</p><button className="primary" onClick={onRegister}>Create a profile to continue</button><button className="text-button" onClick={onLogin}>Already have an account? Sign in</button></div>:available?<button className="primary" disabled={busy} onClick={()=>onOpen(story.id,state)}>{guestAction} <span aria-hidden="true">→</span></button>:<p className="small-note">{actionLabel(state)}</p>}{!user&&state?.mode==='unstarted'&&<p className="small-note">No registration required.</p>}<details className="chapters"><summary>Published chapters <span>{String(publishedCount).padStart(2,'0')}</span></summary>{story.chapters.map((chapter,index)=>{const current=state?.chapterId===chapter.id,completed=state?.mode==='complete'||lastCompletedAt>=index;let chapterStatus='Published';if(completed)chapterStatus='Completed';else if(current&&state?.mode==='active')chapterStatus='In progress';else if(chapter.unlocked||chapter.keyCost===0)chapterStatus='Available';else if(user&&typeof chapter.keyCost==='number')chapterStatus=`${chapter.keyCost} ${chapter.keyCost===1?'Key':'Keys'}`;return <div className="chapter-current" key={chapter.id}><small>{current?'CURRENT CHAPTER':`CHAPTER ${index+1}`}</small><strong>{chapter.title}</strong>{user&&<span>{chapterStatus}</span>}</div>;})}</details></div></article>;
}

export function HomePage({items,states,user,busy,home,actionLabel,onOpen,onRegister,onLogin}:{items:CatalogItem[];states:Record<string,ReadingState>;user:boolean;busy:boolean;home:HomeData;actionLabel:(state?:ReadingState)=>string;onOpen:(id:string,state?:ReadingState)=>void;onRegister:()=>void;onLogin:()=>void}){
 const primary=items.find(item=>item.chapters.some(chapter=>chapter.guestFree))??items[0];if(!primary)return <section className="catalog"><h1>Stories</h1><p>No published stories yet.</p></section>;
 const primaryState=states[primary.id],available=!!primaryState&&primaryState.mode!=='complete';const otherItems=user?items.filter(item=>item.id!==primary.id):[],publishedCount=home.stories.find(story=>story.id===primary.id)?.publishedChapters??primary.chapters.length;
 const scrollPrimary=()=>document.getElementById('featured-story')?.scrollIntoView({behavior:'smooth',block:'start'});
 return <><PageMeta path="/"/><section className="catalog"><div className="catalog-heading"><h1>Stories</h1></div><StoryFeatureCard story={primary} state={primaryState} user={user} busy={busy} publishedCount={publishedCount} actionLabel={actionLabel} onOpen={onOpen} onRegister={onRegister} onLogin={onLogin} featured/></section>
 {!user&&<section className="positioning"><p>We create visual stories so you can do more than watch a character’s life unfold: together with other readers, you can help decide where it turns next.</p></section>}
 {user&&otherItems.length>0&&<section className="home-section other-stories"><h2>Other stories</h2><div className="full-story-list">{otherItems.map(item=><StoryFeatureCard key={item.id} story={item} state={states[item.id]} user busy={busy} publishedCount={item.chapters.length} actionLabel={actionLabel} onOpen={onOpen} onRegister={onRegister} onLogin={onLogin}/>)}</div></section>}
 <section className="home-section stats-section" aria-labelledby="stats-title"><h2 id="stats-title">Published so far</h2><div className="stats-grid">{home.stats.publishedChapters>0&&<div><strong>{home.stats.publishedChapters}</strong><span>Published chapters</span></div>}{home.stats.illustratedScenes>0&&<div><strong>{home.stats.illustratedScenes}</strong><span>Illustrated scenes</span></div>}{home.stats.activePolls>0&&<div><strong>{home.stats.activePolls}</strong><span>Reader decisions</span></div>}</div></section>
 {!user&&<section className="home-section" id="how-it-works"><h2>How it works</h2><div className="steps-grid"><article><span>01</span><h3>Start reading</h3><p>The first chapter is available free, with no registration required.</p></article><article><span>02</span><h3>Join the votes</h3><p>Create a profile so your choice can be counted and saved.</p></article><article><span>03</span><h3>Open the continuation</h3><p>Use Keys to open new chapters and return to them whenever you like.</p></article></div></section>}
 <section className="home-section seo-section"><h2>Visual stories that grow with their readers</h2><p>Storymera is a collection of illustrated fiction combining sequential storytelling, atmospheric imagery, and reader voting. Audience decisions do not create temporary branches; they help determine the direction of future chapters.</p><p>Meet the characters for free, save progress to your profile, take part in votes, and open the continuation of stories you enjoy.</p></section>
 {!user&&<section className="final-cta"><h2>Start with the first chapter</h2><p>Meet Jessica and share her first day in an unfamiliar city.</p><button className="primary" disabled={busy} onClick={()=>available?onOpen(primary.id,primaryState):scrollPrimary()}>Read for free <span aria-hidden="true">→</span></button></section>}</>;
}

type InfoKey='about'|'how-it-works'|'privacy'|'terms'|'contact';
export function InfoPage({kind,contactEmail,onHome}:{kind:InfoKey;contactEmail:string|null;onHome:()=>void}){
 const path='/'+kind;let content;
 if(kind==='about')content=<><h1>About Storymera</h1><p>Storymera is a collection of illustrated, sequential stories. Images set the atmosphere while each scene moves the same chapter forward in a clear order.</p><h2>Stories shaped with readers</h2><p>Selected scenes invite readers to vote. These votes do not split the current chapter into temporary routes. They help the author choose the canonical direction of future chapters.</p><h2>Start freely</h2><p>The first chapter can be read without an account. A profile keeps progress across devices and allows votes to be counted.</p></>;
 else if(kind==='how-it-works')content=<><h1>How it works</h1><h2>1. Read the first chapter free</h2><p>A guest session saves your place on this device and server while you move through every scene in sequence.</p><h2>2. Create a profile when you are ready</h2><p>Registration transfers eligible guest progress to the profile. It lets your poll choices be counted and keeps progress available after signing in elsewhere.</p><h2>3. Continue in order</h2><p>Scenes and chapters open sequentially. A vote never skips a scene or creates a private story branch.</p><h2>4. Use Keys for later chapters</h2><p>One Key unlocks one chapter when that chapter requires a Key. Once unlocked for your profile, that chapter remains available. Keys cannot currently be purchased on this local site.</p><h2>5. Shape future chapters</h2><p>Poll results help determine which option becomes the canonical direction of a future chapter.</p></>;
 else if(kind==='privacy')content=<><h1>Privacy policy</h1><p>This policy describes the current local Storymera prototype and the data it uses to provide reading and voting features.</p><h2>Guest progress</h2><p>A necessary guest-session cookie identifies an anonymous reading session. The server stores the current chapter, last scene, completed scenes, and poll status so reading can resume. This cookie is not used for advertising or analytics.</p><h2>Account data</h2><p>Registration stores an email address and a protected password hash. Passwords are never stored as readable text. Account progress, opened chapters, Key balance, and votes are stored on the server.</p><h2>Votes and technical records</h2><p>The service records poll choices, poll-view events needed for voting statistics, and limited technical logs used to diagnose failures and protect normal operation. It does not use advertising, marketing email, payment, or third-party analytics services.</p><h2>Use and retention</h2><p>Data is used to authenticate accounts, restore reading progress, enforce chapter access, count votes, and maintain the service. Before public launch, the owner must define retention periods and publish a contact address for account and data-deletion requests.</p>{contactEmail&&<p>Requests about account data may be sent to <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p>}</>;
 else if(kind==='terms')content=<><h1>Terms of use</h1><p>Storymera provides illustrated fiction, sequential reading, account progress, reader polls, and chapter access through Keys.</p><h2>Accounts and progress</h2><p>Use accurate account credentials, keep them private, and do not attempt to access another person’s account. The service aims to preserve progress, but temporary interruptions may occur during development.</p><h2>Voting</h2><p>Each account has one current official vote per poll. Polls may close, be archived, or have an official canonical result selected. Votes guide future content but do not guarantee that every option will be produced.</p><h2>Keys and chapter access</h2><p>Keys are used to unlock designated chapters. Access to an unlocked chapter remains associated with the account. Purchasing and payment are not currently available.</p><h2>Content and acceptable use</h2><p>Texts, illustrations, video, and interface materials remain protected by their respective rights. Do not copy, redistribute, interfere with, scrape excessively, or abuse the service. Content may be corrected, replaced, archived, or removed as the project develops.</p><h2>Availability and liability</h2><p>The prototype is provided as available. To the extent permitted by applicable law, the owner is not responsible for indirect loss caused by temporary unavailability or experimental features.</p></>;
 else content=<><h1>Contact</h1>{contactEmail?<><p>For questions about Storymera or account data, email:</p><p><a href={`mailto:${contactEmail}`}>{contactEmail}</a></p></>:<p>Contact details have not been configured. This page will be linked before public launch after the owner adds a real contact address.</p>}</>;
 return <><PageMeta path={path}/><article className="info-page">{content}<button className="text-button" onClick={onHome}>← Back to Stories</button></article></>;
}

export function SiteFooter({authenticated,hasActive,contactAvailable,onNavigate,onLogin,onRegister,onRead,onContinue,onBilling}:{authenticated:boolean;hasActive:boolean;contactAvailable:boolean;onNavigate:Navigate;onLogin:()=>void;onRegister:()=>void;onRead:()=>void;onContinue:()=>void;onBilling:()=>void}){
 const link=(label:string,path:string)=><a href={path} onClick={event=>{event.preventDefault();onNavigate(path);}}>{label}</a>;
 return <footer className="site-footer"><div className="footer-grid"><section><h2>Storymera</h2><p>Visual stories whose direction is shaped with the help of readers.</p></section><nav aria-label="Stories"><h3>Stories</h3>{link('All stories','/')}{link('How it works','/how-it-works')}<button onClick={onRead}>Read the first chapter</button></nav><nav aria-label="Account"><h3>Account</h3>{authenticated?<>{hasActive&&<button onClick={onContinue}>Continue reading</button>}<button onClick={onBilling}>Get Keys</button></>:<><button onClick={onLogin}>Sign in</button><button onClick={onRegister}>Create profile</button></>}</nav><nav aria-label="Information"><h3>Information</h3>{link('About','/about')}{contactAvailable&&link('Contact','/contact')}</nav><nav aria-label="Documents"><h3>Documents</h3>{link('Privacy policy','/privacy')}{link('Terms of use','/terms')}</nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Storymera</span></div></footer>;
}
