import {useEffect,useState} from 'react';
import {api} from './api';

type Source={id:string;displayName:string;source:string;campaign:string|null;publication:string|null;shortCode:string;targetPath:string;shortUrl:string;visibleMetrics:string[];goalType:'none'|'scene'|'chapter_complete';goalHeroineId:string|null;goalChapterId:string|null;goalSceneId:string|null;archived:boolean;synthetic?:boolean};
type Options={heroines:{id:string;name:string}[];chapters:{id:string;heroine_id:string;title:string}[];scenes:{id:string;chapterId:string;title:string}[]};
type ReportRow=Source&{visits:number;visitors:number;started:number|null;completed:number|null;registrations:number|null;goal:number|null};
const empty:Omit<Source,'id'|'shortUrl'|'archived'>={displayName:'',source:'',campaign:null,publication:null,shortCode:'',targetPath:'/',visibleMetrics:['reading_started','chapter_completed','registration_completed','goal'],goalType:'chapter_complete',goalHeroineId:null,goalChapterId:null,goalSceneId:null};
const metric=(value:number|null)=>value===null?'—':String(value);
export function SourceAnalyticsAdmin(){
 const [sources,setSources]=useState<Source[]>([]),[options,setOptions]=useState<Options>({heroines:[],chapters:[],scenes:[]}),[rows,setRows]=useState<ReportRow[]>([]),[total,setTotal]=useState({visits:0,visitors:0,started:0,completed:0,registrations:0,goal:null as number|null});
 const [filter,setFilter]=useState('active'),[period,setPeriod]=useState('7'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[form,setForm]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[status,setStatus]=useState('Loading…'),[busy,setBusy]=useState(false);
 async function load(nextFilter=filter){setBusy(true);try{const query=new URLSearchParams({status:nextFilter,period});if(period==='custom'){query.set('from',from);query.set('to',to);}const [sourceData,optionData,report]=await Promise.all([api('/admin/source-analytics/sources?status='+nextFilter),api('/admin/source-analytics/options'),api('/admin/source-analytics/report?'+query)]);setSources(sourceData);setOptions(optionData);setRows(report.rows);setTotal(report.total);setStatus(`Report ${report.from}–${report.to} · ${report.timezone}`);if(!editing&&!form.goalHeroineId){const hero=optionData.heroines.find((h:any)=>h.name.trim().toLowerCase()==='jessica'),chapter=hero&&optionData.chapters.find((c:any)=>c.heroine_id===hero.id);if(hero&&chapter)setForm((v:any)=>({...v,goalHeroineId:hero.id,goalChapterId:chapter.id}));}}catch(e){setStatus(e instanceof Error?e.message:'Unable to load analytics.');}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 const chapters=options.chapters.filter(c=>c.heroine_id===form.goalHeroineId),scenes=options.scenes.filter(s=>s.chapterId===form.goalChapterId);
 function edit(source?:Source){setEditing(source?.id??null);setForm(source?{...source}:structuredClone(empty));}
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);try{const body={...form,campaign:form.campaign||null,publication:form.publication||null};if(editing)await api('/admin/source-analytics/sources/'+editing,'PATCH',body);else await api('/admin/source-analytics/sources','POST',body);setStatus(editing?'Source configuration saved.':'Source link created.');edit();await load();}catch(e){setStatus(e instanceof Error?e.message:'Unable to save source.');}finally{setBusy(false);}}
 async function archive(source:Source){setBusy(true);try{await api('/admin/source-analytics/sources/'+source.id+'/archive','POST',{archived:!source.archived});await load();}catch(e){setStatus(e instanceof Error?e.message:'Unable to update source.');}finally{setBusy(false);}}
 return <section className="admin-panel source-analytics"><div className="admin-heading"><div><h2>Sources &amp; behavior</h2><p>Configured links, attributed visits and successful reader actions.</p></div><button className="primary" onClick={()=>edit()}>Add source</button></div>
  <div className="analytics-filters"><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="custom">Custom</option></select></label>{period==='custom'&&<><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}<label>Links<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active</option><option value="archived">Archived</option><option value="all">All</option></select></label><button disabled={busy} onClick={()=>void load()}>Apply</button></div>
  <p role="status" className="admin-help">{status}</p>
  <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Source</th><th>Campaign / publication</th><th>Short link</th><th>Visits</th><th>Visitors</th><th>Started</th><th>Completed</th><th>Registrations</th><th>Goal</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.displayName}</strong><br/><span>{row.source}{row.archived?' · Archived':''}</span></td><td>{row.campaign||'—'} / {row.publication||'—'}</td><td>{row.shortUrl?<a href={row.shortUrl} target="_blank" rel="noreferrer">{row.shortUrl}</a>:'—'}</td><td>{row.visits}</td><td>{row.visitors}</td><td>{metric(row.started)}</td><td>{metric(row.completed)}</td><td>{metric(row.registrations)}</td><td>{metric(row.goal)}</td><td>{row.synthetic?'—':<><button onClick={()=>edit(row)}>Configure</button> <button onClick={()=>void archive(row)}>{row.archived?'Restore':'Archive'}</button></>}</td></tr>)}<tr className="analytics-total"><th colSpan={3}>Total</th><td>{total.visits}</td><td>{total.visitors}</td><td>{total.started}</td><td>{total.completed}</td><td>{total.registrations}</td><td>{metric(total.goal)}</td><td>—</td></tr></tbody></table></div>
  <form className="admin-editor analytics-editor" onSubmit={save}><h3>{editing?'Configure source':'Add source'}</h3><div className="analytics-form-grid"><label>Display name<input required maxLength={160} value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>Source<input required maxLength={100} placeholder="youtube" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label><label>Campaign<input maxLength={160} value={form.campaign??''} onChange={e=>setForm({...form,campaign:e.target.value})}/></label><label>Publication<input maxLength={160} value={form.publication??''} onChange={e=>setForm({...form,publication:e.target.value})}/></label><label>Permanent short code<input required disabled={!!editing} pattern="[a-z0-9][a-z0-9-]{1,63}" value={form.shortCode} onChange={e=>setForm({...form,shortCode:e.target.value.toLowerCase()})}/></label><label>Internal target<input required placeholder="/" value={form.targetPath} onChange={e=>setForm({...form,targetPath:e.target.value})}/></label></div>
   <fieldset><legend>Visible metrics</legend>{[['reading_started','Started reading'],['chapter_completed','Completed chapter'],['registration_completed','Registrations'],['goal','Goal']].map(([id,label])=><label className="check" key={id}><input type="checkbox" checked={form.visibleMetrics.includes(id)} onChange={e=>setForm({...form,visibleMetrics:e.target.checked?[...form.visibleMetrics,id]:form.visibleMetrics.filter((x:string)=>x!==id)})}/>{label}</label>)}</fieldset>
   <div className="analytics-form-grid"><label>Goal<select value={form.goalType} onChange={e=>setForm({...form,goalType:e.target.value})}><option value="none">No goal</option><option value="scene">Reach scene</option><option value="chapter_complete">Complete chapter</option></select></label>{form.goalType!=='none'&&<label>Story<select value={form.goalHeroineId??''} onChange={e=>setForm({...form,goalHeroineId:e.target.value||null,goalChapterId:null,goalSceneId:null})}><option value="">Choose…</option>{options.heroines.map(h=><option value={h.id} key={h.id}>{h.name}</option>)}</select></label>}{form.goalType!=='none'&&<label>Chapter<select value={form.goalChapterId??''} onChange={e=>setForm({...form,goalChapterId:e.target.value||null,goalSceneId:null})}><option value="">Choose…</option>{chapters.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label>}{form.goalType==='scene'&&<label>Scene<select value={form.goalSceneId??''} onChange={e=>setForm({...form,goalSceneId:e.target.value||null})}><option value="">Choose…</option>{scenes.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</select></label>}</div>
   <div className="admin-tools"><button className="primary" disabled={busy}>{editing?'Save configuration':'Create source link'}</button>{editing&&<button type="button" onClick={()=>edit()}>Cancel editing</button>}</div></form>
 </section>;
}
